// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAW-dJULmJd9VBaIkcQW0vNtBAjyAjJ8lI',
    appId: '1:778392200653:web:ab6f4e6f1ba9dae290d084',
    messagingSenderId: '778392200653',
    projectId: 'yusr-a5c9b',
    authDomain: 'yusr-a5c9b.firebaseapp.com',
    storageBucket: 'yusr-a5c9b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA21L7tagB1tnWFYTa4qy3oK2GJlqvc4RE',
    appId: '1:778392200653:android:0b4d1471841b5b7e90d084',
    messagingSenderId: '778392200653',
    projectId: 'yusr-a5c9b',
    storageBucket: 'yusr-a5c9b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGTuFOw1UgGlDVVDrLmI2gLJRlDAP2O3o',
    appId: '1:778392200653:ios:0dc17ac60752487690d084',
    messagingSenderId: '778392200653',
    projectId: 'yusr-a5c9b',
    storageBucket: 'yusr-a5c9b.appspot.com',
    iosClientId: '778392200653-et177hal81c8fhf7tvldvo13gd21bd9u.apps.googleusercontent.com',
    iosBundleId: 'com.example.gpyusr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGTuFOw1UgGlDVVDrLmI2gLJRlDAP2O3o',
    appId: '1:778392200653:ios:0dc17ac60752487690d084',
    messagingSenderId: '778392200653',
    projectId: 'yusr-a5c9b',
    storageBucket: 'yusr-a5c9b.appspot.com',
    iosClientId: '778392200653-et177hal81c8fhf7tvldvo13gd21bd9u.apps.googleusercontent.com',
    iosBundleId: 'com.example.gpyusr',
  );
}
